export const FETCH_ROOMS_BEGIN = 'FETCH_ROOMS_BEGIN'
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS'
export const FETCH_ROOMS_FAILED = 'FETCH_ROOMS_FAILED'

export const ROOM_ADDED = 'ROOM_ADDED'
export const ROOM_MODIFIED = 'ROOM_MODIFIED'
export const ROOM_REMOVED = 'ROOM_REMOVED'

export const CREATE_ROOM_BEGIN = 'CREATE_ROOM_BEGIN'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED'
